name = 'new2026'
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "b696aa350f3f4ef2816fcdd872b32065"          #KV据库id
